### ISSUE TITLE
broken dependency on wabashd-shell

### ISSUE THREAD

**Issue by valeryan** [cerebrate/wsl-translinux#4]
I wanted try out the wabashd-shell version that was added by @heldchen from pull request https://github.com/cerebrate/wsl-translinux/pull/2. However, It has a bash dependency that does not seem to match up on wsl. 

I get this error:

```
wabashd-shell depends on bash (>= 4.3.0); however:
  Version of bash on system is 4.3-14ubuntu1.2.

Depends: bash (>= 4.3.0) but 4.3-14ubuntu1.2 is to be installed
```
My bash version installed is `GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)`

I downloaded the deb file and installed it anyway using 

`sudo dpkg --force-depends -i wabashd-shell_4.0.1_all.deb` to continue testing with it.

**Comment by heldchen** [comment]
thanks for reporting this. it is currently using
`Depends: bash (>= 4.3.0)`
but I guess it should be relaxed to
`Depends: bash (>= 4)`
I'll test this and create a new version tomorrow.

**Comment by heldchen** [comment]
added PR for the updated deb. in the meantime, you can download it here: https://github.com/alternize/wabashd-shell/releases

**Comment by cerebrate** [comment]
Thanks for the PR. I'll merge it as soon as I get a minute.
